#!/bin/bash

NAME=fastapi-app
DIR=/home/ksuser/Bhautik/APIs/Speech_to_text_api/
USER=ksuser
GROUP= ksuser
WORKERS=3
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV= /home/ksuser/ml/bin/activate
BIND= unix:$DIR/run/gunicorn.sock
LOG_LEVEL= error

cd $DIR
source $VENV

exec gunicorn main:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-

